
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPAREN NUMBER RPAREN SYMBOLexpression : NUMBERexpression : SYMBOLexpression : LPAREN list RPARENlist :list : expression list'
    
_lr_action_items = {'NUMBER':([0,2,3,4,6,7,],[2,-1,-2,2,2,-3,]),'SYMBOL':([0,2,3,4,6,7,],[3,-1,-2,3,3,-3,]),'LPAREN':([0,2,3,4,6,7,],[4,-1,-2,4,4,-3,]),'$end':([1,2,3,7,],[0,-1,-2,-3,]),'RPAREN':([2,3,4,5,6,7,8,],[-1,-2,-4,7,-4,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,6,],[1,6,6,]),'list':([4,6,],[5,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',36),
  ('expression -> SYMBOL','expression',1,'p_expression_symbol','parser.py',40),
  ('expression -> LPAREN list RPAREN','expression',3,'p_expression_list','parser.py',44),
  ('list -> <empty>','list',0,'p_list_empty','parser.py',48),
  ('list -> expression list','list',2,'p_list_nonempty','parser.py',52),
]
